#!/bin/bash

echo "🚀 Pushing Claude Tools Kit to GitHub"
echo "===================================="
echo ""
echo "Option 1: Using SSH (if you have SSH key set up)"
echo "================================================"
echo "Run these commands:"
echo ""
echo "cd ~/claude-tools-kit"
echo "git remote set-url origin git@github.com:broneotodak/claude-tools-kit.git"
echo "git push -u origin main"
echo ""
echo "Option 2: Using HTTPS with Personal Access Token"
echo "==============================================="
echo "1. Create a Personal Access Token at:"
echo "   https://github.com/settings/tokens/new"
echo "   - Select 'repo' scope"
echo "   - Copy the token"
echo ""
echo "2. Then run:"
echo "cd ~/claude-tools-kit"
echo "git remote set-url origin https://github.com/broneotodak/claude-tools-kit.git"
echo "git push -u origin main"
echo "   - Username: broneotodak"
echo "   - Password: [paste your token]"
echo ""
echo "Option 3: Using GitHub CLI (if installed)"
echo "========================================"
echo "gh auth login"
echo "cd ~/claude-tools-kit"
echo "git push -u origin main"
echo ""
echo "📁 Your local repository is at: ~/claude-tools-kit"
echo "🌐 Remote repository: https://github.com/broneotodak/claude-tools-kit"