#!/bin/bash

# Setup CTK on a new machine
# This ensures consistent memory capture across different environments

echo "🚀 Setting up CTK on new machine..."

# Get machine info
MACHINE_NAME=$(hostname)
PLATFORM=$(uname -s)

echo "📍 Machine: $MACHINE_NAME"
echo "🖥️  Platform: $PLATFORM"

# Create local CLAUDE.md for this machine
cat > CLAUDE.md << EOF
# Claude Code Configuration
## Machine: $MACHINE_NAME
## Platform: $PLATFORM
## Initialized: $(date +%Y-%m-%d)

### Machine-Specific Notes
- Machine Name: $MACHINE_NAME
- This will be normalized to a standard name by CTK enrichment
- All memories from this machine will be automatically enriched

### Memory Capture
- Git hooks will capture as: $MACHINE_NAME
- CTK enrichment will normalize based on patterns
- Add custom rules in memory-enrichment-rules.js if needed

### Quick Start
1. Save memories as usual - machine name will be captured
2. Enrichment runs every 5 minutes to standardize
3. FlowState will display normalized machine names

---
*Generated by setup-new-machine.sh*
EOF

echo "✅ Created machine-specific CLAUDE.md"

# Install git hooks
if [ -f "./tools/install-working-git-hooks.sh" ]; then
    echo "📎 Installing git hooks..."
    ./tools/install-working-git-hooks.sh
fi

# Setup cron for enrichment
if [ -f "./tools/setup-memory-enrichment-cron.sh" ]; then
    echo "⏰ Setting up memory enrichment cron..."
    ./tools/setup-memory-enrichment-cron.sh
fi

echo ""
echo "✨ CTK setup complete for $MACHINE_NAME!"
echo ""
echo "📝 Next steps:"
echo "1. Memories will be saved with machine name: $MACHINE_NAME"
echo "2. Enrichment will normalize to standard names"
echo "3. Add custom rules in tools/memory-enrichment-rules.js if needed"
echo ""
echo "Example: If this is your office PC, add to MACHINE_RULES:"
echo "  { pattern: /$MACHINE_NAME/i, normalized: 'Office PC' }"